site_name: Grupo 8 - 

theme:
  name: material
  language: pt

nav:
  - Início: index.md
  - Planejamento: 
    - Cronograma: ./planejamento/cronograma.md
    - Ferramentas: ./planejamento/ferramentas.md
    - Metodologias: ./planejamento/scrum_adaptado.md