site_name: Grupo 8 - Twitch
repo_url: https://github.com/Requisitos-de-Software/2023.1-Twitch
repo_name: Requisitos-de-Software/2023.1-Twitch

theme:
  name: material
  language: pt
  logo: ./planejamento/imagens/twitch_icon.png
  favicon: ./planejamento/imagens/twitch_icon.png
  features:
    - navigation.footer
    - header.autohide

  plugins:
    - mkdocs-video
  
  favicon: ./assets/twitch_icon.png
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Início: index.md
  - Planejamento:   
    - Cronograma: ./planejamento/cronograma.md
    - Cronograma Realizado: ./planejamento/cronograma_realizado.md
    - Ferramentas: ./planejamento/ferramentas.md
    - Metodologias: ./planejamento/scrum_adaptado.md
  - Pré-Rastreabilidade:
    - Rich Picture: ./pre_rastreabilidade/rich_picture.md
  - Elicitação:
    - Perfis de Usuário: ./elicitacao/perfis_usuario.md
    - Personas: ./elicitacao/personas.md
    - Técnicas:
      - Brainstorm: ./elicitacao/tecnicas/Brainstorm.md
      - Observação: ./elicitacao/tecnicas/observacao.md
      - Análise Documental: ./elicitacao/tecnicas/AnaliseDeDocumento.md
    - Priorização: ./elicitacao/priorizacao.md
  - Modelagem: 
    - Cenários: ./modelagem/cenarios.md
    - Léxico: ./modelagem/lexico.md
    - Use Case: ./modelagem/usecase.md
    - Especificação Suplementar: ./modelagem/esp_suplementar.md
    - User Stories: ./modelagem/user_stories.md
  - Atas de reunião: 
    - Reunião 1: ./atas/reuniao_1.md
    - Reunião 2: ./atas/reuniao_2.md
    - Reunião 3: ./atas/reuniao_3.md
    - Reunião 4: ./atas/reuniao_4.md
    - Reunião 5: ./atas/reuniao_5.md
    - Reunião 6: ./atas/reuniao_6.md
  - Apresentações: ./apresentacoes.md
  - Regras de Colaboração: ./colab.md

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
