site_name: Grupo 8 - Twitch
repo_url: https://github.com/Requisitos-de-Software/2023.1-Twitch
repo_name: Requisitos-de-Software/2023.1-Twitch

theme:
  name: material
  language: pt
  logo: ./planejamento/imagens/twitch_icon.png
  favicon: ./planejamento/imagens/twitch_icon.png
  features:
    - navigation.footer
    - header.autohide
  
nav:
  - Início: index.md
  - Planejamento: 
    - Cronograma: ./planejamento/cronograma.md
    - Ferramentas: ./planejamento/ferramentas.md
    - Metodologias: ./planejamento/scrum_adaptado.md